package com.totoro.db.dao;

import com.totoro.db.entity.Coupon;

import java.util.List;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    Coupon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Coupon record);




    /**
     * 查询某用户优惠券数量
     * @param userId
     * @return
     */
    int selectCountByUserId(Long userId);

    /**
     * 查询某用户的优惠券
     *
     * @param id
     * @return
     */
    List<Coupon> listCouponsByUserId(Long id);

    /**
     * 根据cdKey查询优惠券
     *
     * @param cdKey
     * @return
     */
    Coupon selectByCdKey(String cdKey);
}