package com.totoro.db.dao;

import com.totoro.db.entity.DailySpecial;

import java.util.List;

public interface DailySpecialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    int insert(DailySpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    int insertSelective(DailySpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    DailySpecial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DailySpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DailySpecial record);




    /**
     *
     * 查询所有当日特价商品
     *
     * @return List<DailySpecial>
     */
    List<DailySpecial> selectByEffectiveDate();
}