package com.totoro.db.dao;

import com.totoro.db.entity.DailyChoice;

import java.util.List;

public interface DailyChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    int insert(DailyChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    int insertSelective(DailyChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    DailyChoice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DailyChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DailyChoice record);




    /**
     * 查询所有每日精选商品
     *
     * @return List<DailyChoice>
     */
    List<DailyChoice> selectAll();
}