package com.totoro.db.dao;

import com.totoro.db.entity.TotoroChoice;

public interface TotoroChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_choice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_choice
     *
     * @mbg.generated
     */
    int insert(TotoroChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_choice
     *
     * @mbg.generated
     */
    int insertSelective(TotoroChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_choice
     *
     * @mbg.generated
     */
    TotoroChoice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_choice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TotoroChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_choice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TotoroChoice record);
}