package com.totoro.db.dao;

import com.totoro.db.entity.TotoroSeckill;

public interface TotoroSeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    int insert(TotoroSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    int insertSelective(TotoroSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    TotoroSeckill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TotoroSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TotoroSeckill record);
}