package com.totoro.db.dao;

import com.totoro.db.entity.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);



    /**
     * 根据 nickname 查询用户信息
     * @param nickname nickname
     * @return UserInfo
     */
    UserInfo selectByNickname(String nickname);

    /**
     * 根据 phone 查询用户信息
     * @param phone phone
     * @return UserInfo
     */
    UserInfo selectByPhone(String phone);

    /**
     * 根据 email 查询用户信息
     * @param email email
     * @return UserInfo
     */
    UserInfo selectByEmail(String email);

    /**
     * 根据token 查询用户信息
     *
     * @param token token
     * @return UserInfo
     */
    UserInfo selectByToken(String token);
}