package com.totoro.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table daily_choice
 */
public class DailyChoice implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_choice.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   精选商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_choice.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   入选理由
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_choice.choice_reason
     *
     * @mbg.generated
     */
    private String choiceReason;

    /**
     * Database Column Remarks:
     *   精选标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_choice.choice_tag
     *
     * @mbg.generated
     */
    private String choiceTag;

    /**
     * Database Column Remarks:
     *   展示顺序【0：优先级最高】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_choice.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_choice.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_choice.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_choice.id
     *
     * @return the value of daily_choice.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_choice.id
     *
     * @param id the value for daily_choice.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_choice.product_id
     *
     * @return the value of daily_choice.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_choice.product_id
     *
     * @param productId the value for daily_choice.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_choice.choice_reason
     *
     * @return the value of daily_choice.choice_reason
     *
     * @mbg.generated
     */
    public String getChoiceReason() {
        return choiceReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_choice.choice_reason
     *
     * @param choiceReason the value for daily_choice.choice_reason
     *
     * @mbg.generated
     */
    public void setChoiceReason(String choiceReason) {
        this.choiceReason = choiceReason == null ? null : choiceReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_choice.choice_tag
     *
     * @return the value of daily_choice.choice_tag
     *
     * @mbg.generated
     */
    public String getChoiceTag() {
        return choiceTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_choice.choice_tag
     *
     * @param choiceTag the value for daily_choice.choice_tag
     *
     * @mbg.generated
     */
    public void setChoiceTag(String choiceTag) {
        this.choiceTag = choiceTag == null ? null : choiceTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_choice.priority
     *
     * @return the value of daily_choice.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_choice.priority
     *
     * @param priority the value for daily_choice.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_choice.create_time
     *
     * @return the value of daily_choice.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_choice.create_time
     *
     * @param createTime the value for daily_choice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_choice.update_time
     *
     * @return the value of daily_choice.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_choice.update_time
     *
     * @param updateTime the value for daily_choice.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_choice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", choiceReason=").append(choiceReason);
        sb.append(", choiceTag=").append(choiceTag);
        sb.append(", priority=").append(priority);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}