package com.totoro.db.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table daily_special
 */
public class DailySpecial implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   秒杀商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   展示顺序【0：优先级最高】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     * Database Column Remarks:
     *   原始价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.origin_price
     *
     * @mbg.generated
     */
    private BigDecimal originPrice;

    /**
     * Database Column Remarks:
     *   秒杀价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.discount_price
     *
     * @mbg.generated
     */
    private BigDecimal discountPrice;

    /**
     * Database Column Remarks:
     *   特价时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.effective_date
     *
     * @mbg.generated
     */
    private LocalDate effectiveDate;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_special.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.id
     *
     * @return the value of daily_special.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.id
     *
     * @param id the value for daily_special.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.product_id
     *
     * @return the value of daily_special.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.product_id
     *
     * @param productId the value for daily_special.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.priority
     *
     * @return the value of daily_special.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.priority
     *
     * @param priority the value for daily_special.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.origin_price
     *
     * @return the value of daily_special.origin_price
     *
     * @mbg.generated
     */
    public BigDecimal getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.origin_price
     *
     * @param originPrice the value for daily_special.origin_price
     *
     * @mbg.generated
     */
    public void setOriginPrice(BigDecimal originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.discount_price
     *
     * @return the value of daily_special.discount_price
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.discount_price
     *
     * @param discountPrice the value for daily_special.discount_price
     *
     * @mbg.generated
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.effective_date
     *
     * @return the value of daily_special.effective_date
     *
     * @mbg.generated
     */
    public LocalDate getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.effective_date
     *
     * @param effectiveDate the value for daily_special.effective_date
     *
     * @mbg.generated
     */
    public void setEffectiveDate(LocalDate effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.create_time
     *
     * @return the value of daily_special.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.create_time
     *
     * @param createTime the value for daily_special.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_special.update_time
     *
     * @return the value of daily_special.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_special.update_time
     *
     * @param updateTime the value for daily_special.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_special
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", priority=").append(priority);
        sb.append(", originPrice=").append(originPrice);
        sb.append(", discountPrice=").append(discountPrice);
        sb.append(", effectiveDate=").append(effectiveDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}