package com.totoro.db.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table totoro_seckill
 */
public class TotoroSeckill implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   秒杀商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   秒杀开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.start_time
     *
     * @mbg.generated
     */
    private LocalDateTime startTime;

    /**
     * Database Column Remarks:
     *   秒杀结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     * Database Column Remarks:
     *   原始价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.origin_price
     *
     * @mbg.generated
     */
    private BigDecimal originPrice;

    /**
     * Database Column Remarks:
     *   秒杀价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.discount_price
     *
     * @mbg.generated
     */
    private BigDecimal discountPrice;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column totoro_seckill.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.id
     *
     * @return the value of totoro_seckill.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.id
     *
     * @param id the value for totoro_seckill.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.product_id
     *
     * @return the value of totoro_seckill.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.product_id
     *
     * @param productId the value for totoro_seckill.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.start_time
     *
     * @return the value of totoro_seckill.start_time
     *
     * @mbg.generated
     */
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.start_time
     *
     * @param startTime the value for totoro_seckill.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.end_time
     *
     * @return the value of totoro_seckill.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.end_time
     *
     * @param endTime the value for totoro_seckill.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.origin_price
     *
     * @return the value of totoro_seckill.origin_price
     *
     * @mbg.generated
     */
    public BigDecimal getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.origin_price
     *
     * @param originPrice the value for totoro_seckill.origin_price
     *
     * @mbg.generated
     */
    public void setOriginPrice(BigDecimal originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.discount_price
     *
     * @return the value of totoro_seckill.discount_price
     *
     * @mbg.generated
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.discount_price
     *
     * @param discountPrice the value for totoro_seckill.discount_price
     *
     * @mbg.generated
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.create_time
     *
     * @return the value of totoro_seckill.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.create_time
     *
     * @param createTime the value for totoro_seckill.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column totoro_seckill.update_time
     *
     * @return the value of totoro_seckill.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column totoro_seckill.update_time
     *
     * @param updateTime the value for totoro_seckill.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table totoro_seckill
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", originPrice=").append(originPrice);
        sb.append(", discountPrice=").append(discountPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}