package com.totoro.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_address
 */
public class UserAddress implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   地址所属国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   地址所属省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   地址所属城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   详细地址信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     * Database Column Remarks:
     *   地址标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     * Database Column Remarks:
     *   收货人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     * Database Column Remarks:
     *   收货人手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.receiver_number
     *
     * @mbg.generated
     */
    private String receiverNumber;

    /**
     * Database Column Remarks:
     *   地址对应的用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   是否为默认地址【0：不是、1：是】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.default_address
     *
     * @mbg.generated
     */
    private Byte defaultAddress;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_address
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.country
     *
     * @return the value of user_address.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.country
     *
     * @param country the value for user_address.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.province
     *
     * @return the value of user_address.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.province
     *
     * @param province the value for user_address.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.city
     *
     * @return the value of user_address.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.city
     *
     * @param city the value for user_address.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.detail
     *
     * @return the value of user_address.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.detail
     *
     * @param detail the value for user_address.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.tag
     *
     * @return the value of user_address.tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.tag
     *
     * @param tag the value for user_address.tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver
     *
     * @return the value of user_address.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver
     *
     * @param receiver the value for user_address.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.receiver_number
     *
     * @return the value of user_address.receiver_number
     *
     * @mbg.generated
     */
    public String getReceiverNumber() {
        return receiverNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.receiver_number
     *
     * @param receiverNumber the value for user_address.receiver_number
     *
     * @mbg.generated
     */
    public void setReceiverNumber(String receiverNumber) {
        this.receiverNumber = receiverNumber == null ? null : receiverNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.default_address
     *
     * @return the value of user_address.default_address
     *
     * @mbg.generated
     */
    public Byte getDefaultAddress() {
        return defaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.default_address
     *
     * @param defaultAddress the value for user_address.default_address
     *
     * @mbg.generated
     */
    public void setDefaultAddress(Byte defaultAddress) {
        this.defaultAddress = defaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.create_time
     *
     * @return the value of user_address.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.create_time
     *
     * @param createTime the value for user_address.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.update_time
     *
     * @return the value of user_address.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.update_time
     *
     * @param updateTime the value for user_address.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", country=").append(country);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", detail=").append(detail);
        sb.append(", tag=").append(tag);
        sb.append(", receiver=").append(receiver);
        sb.append(", receiverNumber=").append(receiverNumber);
        sb.append(", userId=").append(userId);
        sb.append(", defaultAddress=").append(defaultAddress);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}